### ISSUE TITLE
Wide view

### ISSUE THREAD

**Issue by wheelq** [continuouscalendar/jquery-continuous-calendar#93]
Is there an option to show all days (1..31) in one row? so 12 months would fit in 12 rows

**Comment by eeroan** [comment]
Unfortunately not. This component fits best to use cases like "next monday" or "two weeks ago". Out of curiosity, why would you wan't to do that?

**Comment by wheelq** [comment]
I have limited height but unlimited width, hence 1-31 would fit perfectly :)
